// Generated by dia2code
#ifndef STATE__BOARD__H
#define STATE__BOARD__H


namespace state {
  class Card;
  class Player;
}

#include "Card.h"
#include "Player.h"

namespace state {

  /// class Board - 
  class Board {
    // Attributes
  private:
    vector<Card> lineup;
    // Operations
  public:
    random_init ();
    move_player (Player player, int location);
    vector<Player> get_neighbours (Player player);
    // Setters and Getters
  };

};

#endif
