// Generated by dia2code
#ifndef STATE__CARD__H
#define STATE__CARD__H


namespace state {
  class Vision;
  class Darknlight;
}

#include "Vision.h"
#include "Darknlight.h"

namespace state {

  /// class Card - 
  class Card : public state::Vision, public state::Darknlight {
    // Attributes
  private:
    int* disponible;
    // Operations
  public:
    activate_effect ();
    // Setters and Getters
  };

};

#endif
