// Generated by dia2code
#ifndef STATE__CARD_TYPE__H
#define STATE__CARD_TYPE__H


namespace state {

  // enumerate
  /// class Card_type - 
  class Card_type {
    // Setters and Getters
  };

};

#endif
