// Generated by dia2code
#ifndef STATE__CHARACTER __H
#define STATE__CHARACTER __H


namespace state {
  class Player;
}

#include "Player.h"

namespace state {

  // enumerate
  /// class Character  - 
  class Character  {
    // Attributes
  public:
     ;
    // Setters and Getters
  };

};

#endif
