// Generated by dia2code
#ifndef STATE__CLASS__H
#define STATE__CLASS__H


namespace state {
  class Game;
}

#include "Game.h"

namespace state {

  // enumerate
  /// class Class - 
  class Class {
    // Attributes
  public:
     DARK;
     LIGHT;
     VISION;
    // Setters and Getters
  };

};

#endif
