// Generated by dia2code
#ifndef STATE__DARKNLIGHT__H
#define STATE__DARKNLIGHT__H


namespace state {
  class Card_type;
  class DeckDark;
  class DeckLight;
}

#include "Card_type.h"
#include "DeckDark.h"
#include "DeckLight.h"

namespace state {

  /// class Darknlight - 
  class Darknlight {
    // Attributes
  public:
    Card_type card_type;
  private:
     card_id;
    enum effect;
     is_equipped;
    // Setters and Getters
  };

};

#endif
