// Generated by dia2code
#ifndef STATE__DECKDARK__H
#define STATE__DECKDARK__H


namespace state {
  class Darknlight;
  class Card_type;
  class Game;
}

#include "Darknlight.h"
#include "Card_type.h"
#include "Game.h"

namespace state {

  /// class DeckDark - 
  class DeckDark {
    // Attributes
  private:
    vector<Darknlight> deck;
    // Operations
  public:
    remove (int card_id);
    new_card (Card_type card_type);
    // Setters and Getters
  };

};

#endif
