// Generated by dia2code
#ifndef STATE__DECKVISION__H
#define STATE__DECKVISION__H


namespace state {
  class Vision;
  class Game;
}

#include "Vision.h"
#include "Game.h"

namespace state {

  /// class DeckVision - 
  class DeckVision {
    // Attributes
  private:
    vector<Vision> deck;
    // Operations
  public:
    remove (int card_id);
    // Setters and Getters
  };

};

#endif
