// Generated by dia2code
#ifndef STATE__PLAYER__H
#define STATE__PLAYER__H


namespace state {
  class Player;
}


namespace state {

  /// class Player - 
  class Player {
    // Attributes
  private:
    Character character;
    bool is_a_bot;
    int hp;
    bool revealed;
    int number;
    // Operations
  public:
    move ();
    attack (Player target);
    active_character_effect ();
    show_character_effect ();
    show_cards ();
    active_card (int card_number);
    reveal ();
    // Setters and Getters
  };

};

#endif
